# Generated by Django 5.0.4 on 2024-04-13 20:53

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizacion', models.DateTimeField(auto_created=True)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('contenido', tinymce.models.HTMLField()),
                ('descripcion', models.CharField(max_length=255)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(blank=True, choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('eliminado', 'Eliminado')], default='Publicado', max_length=20)),
                ('slug', models.SlugField(unique=True)),
                ('imagen', models.ImageField(blank=True, default='app_blog/default.png', upload_to='app_blog')),
                ('contador_comentarios', models.IntegerField(default=0)),
                ('contador_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizacion', models.DateTimeField(auto_created=True)),
                ('autor', models.CharField(max_length=30)),
                ('contenido', models.TextField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('contador_likes', models.IntegerField(default=0)),
                ('articulo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_blog.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.post')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.category')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(through='app_blog.PostCategory', to='app_blog.category'),
        ),
    ]
