# Generated by Django 5.0.4 on 2024-04-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias'
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(through='app_blog.PostCategory', to='app_blog.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
