# Generated by Django 5.0.4 on 2024-04-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_post_categorias_delete_postcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.post')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorias'
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(through='app_blog.PostCategory', to='app_blog.category'),
        ),
    ]
