# Generated by Django 5.0.4 on 2024-04-17 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_blog", "0003_postcategory_alter_post_categorias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="articulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="actualizacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
