# Generated by Django 5.0.4 on 2024-04-24 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_blog", "0005_customuser_alter_comment_autor_alter_post_autor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="fecha_nac",
            new_name="dob",
        ),
    ]
