# Generated by Django 5.0.4 on 2024-04-23 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_customuser_alter_comment_autor_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contador_visualizaciones',
            field=models.IntegerField(default= 0),
            preserve_default=False,
        ),
    ]
