# Generated by Django 5.0.4 on 2024-04-25 00:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_blog", "0006_rename_fecha_nac_customuser_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
