# Generated by Django 5.0.4 on 2024-04-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_post_contador_visualizaciones'),
        ('app_blog', '0007_alter_customuser_bio'),
    ]

    operations = [
    ]
