# Generated by Django 5.0.4 on 2024-04-29 00:47

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_merge_20240426_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contador_visualizaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
