# Generated by Django 5.0.4 on 2024-05-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_alter_post_contador_visualizaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='actualizacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
